name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4 for Node.js 20
      - uses: actions/setup-node@v4  # Updated to v4 for Node.js 20
        with:
          node-version: 20.11.1
      - run: npm ci
        working-directory: .
      - run: npm run build --if-present
        working-directory: .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        run: echo "Tests are running"

  docker:
    name: Build Docker image and push to repositories (with cache)
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: ${{ ! needs.docker.outputs.is_cached }}  # Push only if not cached
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            quynt/gitops01:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: nguyentuquy/gitops-infra
          ref: main
          token: ${{ secrets.GHA_TOKEN }}
      - name: Setup Git Config
        run: |
          git config --global user.email "nguyentuquynb@gmail.com"
          git config --global user.name "quy1990"
      - name: Update Deployment Manifest
        run: |
          sed -i 's#quynt.*#quynt/gitops01:${{ github.sha }}#g' deployment.yaml

          git add deployment.yaml
          git commit -m "Updated image: quynt/gitops01:${{github.sha}}"
          git push origin main