name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - test
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap

      # Build Docker image using Buildx with cache
      - name: Build Docker image with Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            -t myimage:latest .
      
      # Push Docker image to repository
      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push myimage:latest

  update-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: nguyentuquy/gitops-infra
          ref: main
          token: ${{ secrets.GHA_TOKEN }}

      # Update Deployment Manifest
      - name: Update Deployment Manifest
        run: |
          git config --global user.email "nguyentuquynb@gmail.com"
          git config --global user.name "quy1990"
          if [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/main' ]; then
            ref_branch='main'
          elif [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/dev' ]; then
            ref_branch='dev'
          elif [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/test' ]; then
            ref_branch='test'
          elif [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/qa' ]; then
            ref_branch='qa'
          else
            ref_branch='dev'
          fi
          git checkout $ref_branch
          sed -i 's#quynt.*#quynt/gitops01:${{ github.sha }}#g' deployment.yaml
          git add deployment.yaml
          git commit -m "Updated image: quynt/gitops01:${{github.sha}}"
          git push origin $ref_branch