name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4 for Node.js 20
      - uses: actions/setup-node@v4  # Updated to v4 for Node.js 20
        with:
          node-version: 20.11.1
      - run: npm ci
        working-directory: .
      - run: npm run build --if-present
        working-directory: .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        run: echo "Tests are running"

  docker:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            quynt/gitops01:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: nguyentuquy/gitops-infra
          ref: main
          token: ${{ secrets.GHA_TOKEN }}
      - name: Setup Git Config
        run: |
          git config --global user.email "nguyentuquynb@gmail.com"
          git config --global user.name "quy1990"
      - name: Update Deployment Manifest
        run: |
          commit_sha=${{ github.sha }}
          sed -i 's#quynt.*#quynt/gitops01:${commit_sha}#g' deployment.yaml
          git add deployment.yaml
          git commit -m "Update image to quynt/gitops01:${commit_sha}"
          git push origin main