name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - test
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Thực hiện parallel jobs cho npm install và build
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build --if-present
        working-directory: .

      # Parallel job để chạy các tests
      - name: Run Tests
        run: echo "Tests are running"

  docker:
    name: Build Docker image and push to repositories (with cache)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            quynt/gitops01:${{ github.sha }}

  update-manifest:
    name: Update Deployment Manifest
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: nguyentuquy/gitops-infra
          ref: main
          token: ${{ secrets.GHA_TOKEN }}
      - name: Setup Git Config
        run: |
          git config --global user.email "nguyentuquynb@gmail.com"
          git config --global user.name "quy1990"
          if [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/main' ]; then
            ref_branch='main'
          elif [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/dev' ]; then
            ref_branch='dev'
          elif [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/test' ]; then
            ref_branch='test'
          elif [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/qa' ]; then
            ref_branch='qa'
          else
            ref_branch='dev'
          fi
          git checkout $ref_branch
      - name: Update Deployment Manifest
        run: |
          sed -i 's#quynt.*#quynt/gitops01:${{ github.sha }}#g' deployment.yaml
          git add deployment.yaml
          git commit -m "Updated image: quynt/gitops01:${{github.sha}}"
          git push origin $ref_branch